server:
  port: 8889
    #servlet:
  #context-path: /public_welfare
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:com/pm/background/**/mapping/*.xml
  type-aliases-package: com.pm.background.**.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  profiles:
    active: @spring.active@
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 23MB
      # 设置总上传的文件大小
      max-request-size: 23MB


    # 设置404抛出异常  404异常为NoHandlerFoundException
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

---

spring:
  profiles: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 10
    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.188:3306/zhongguancundb1?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false
    username: root
    password: root
logging:
  level:
    com.pm.background: debug

---
spring:
  profiles: test
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redispass123
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 10
    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.99.205.211:3306/zhongguancundb?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false
    username: root
    password: root
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 300000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

logging:
  level:
    root: warn
    com.pm.background: warn
---
spring:
  profiles: prod
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redispass123
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 10
    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.99.205.211:3306/zhongguancundb?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false
    username: root
    password: root

logging:
  level:
    root: error
    com.pm.background: error
